site_name: External DNS Hetzner Webhook
site_url: https://mconfalonieri.github.io/external-dns-hetzner-webhook/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Requirements: requirements.md
  - Deployment: deployment.md
  - Environment variables: environment-variables.md
  - Upgrading: upgrading.md
  - Endpoints: endpoints.md
  - Metrics: metrics.md
  - Advanced features: advanced-features.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  version:
    provider: mike

plugins:
  - search
