site_name: (UNOFFICIAL) External DNS Hetzner Webhook
site_url: https://mconfalonieri.github.io/external-dns-hetzner-webhook/

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand

nav:
  - Home: index.md
  - Getting started:
    - Requirements: requirements.md
    - Deployment: deployment.md
    - Upgrading from prevoius versions: upgrading.md
  - Configuration:
    - Environment variables: environment-variables.md
  - Beyond basic usage:
    - Endpoints: endpoints.md
    - Metrics: metrics.md
    - Advanced features: advanced-features.md
  - External resources:
    - Source code: https://github.com/mconfalonieri/external-dns-hetzner-webhook
    - Releases: https://github.com/mconfalonieri/external-dns-hetzner-webhook/releases
    - Packages: https://github.com/mconfalonieri/external-dns-hetzner-webhook/pkgs/container/external-dns-hetzner-webhook


markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences

extra:
  version:
    provider: mike
  image_tag: !ENV [CURRENT_VERSION, "localbuild"]

plugins:
  - mike
  - search
  - macros
