name: Test Report
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-22.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Git Fetch
      run: git fetch --force --tags
    - name: Setup go
      uses: actions/setup-go@v4
      with:
        go-version: stable
    - name: Run Unit Tests
      run: make unit-test
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: unit-test-reports
        path: ./build/reports/**
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()
      with:
        name: Unit Test Results
        artifact: unit-test-reports
        path: ./build/reports/**-test.xml
        reporter: java-junit
        fail-on-error: 'true'
