name: Test Report
on:
  workflow_run:
    workflows: ['CI']                     # runs after CI workflow
    types:
      - completed
permissions:
  contents: read
  actions: read
  checks: write
jobs:
  report:
    runs-on: ubuntu-24.04
    steps:
    - name: Checkout Code
      uses: actions/checkout@v5
      with:
        fetch-depth: 0
    - name: Git Fetch
      run: git fetch --force --tags
    - name: Setup go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'
    - name: Run Unit Tests
      run: make unit-test
    - name: Test Report
      uses: dorny/test-reporter@v2
      if: success() || failure()
      with:
        name: Unit Test Results
        path: ./build/reports/**-test.xml
        reporter: java-junit
        fail-on-error: 'true'
    - name: Upload Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-reports
        path: ./build/reports/**
